# Default values for finaiservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ulihdocker/bn-fin-ai
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: "finaiservice"
fullnameOverride: "finaiservice"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000    
  selector:
    app: finaiservice

proxy: edge

env:
  REDIS_URL: redis-master.default.svc.cluster.local:6379
  LOG_LEVEL: INFO
  MAX_TRIALS: 100
  CONNECTION_STRING: postgresql://bnproject_user:L7n1P2pp0%3F%3F13@192.168.178.74:5432/bn_finai_dev


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false

ingress:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
